name: "MSBuild"

on:
  pull_request:
    branches: 
      - master
      - github-actions
  push:
    branches: 
      - master
      - github-actions

env:
  # Path to the solution file relative to the root of the project.
  MINEWAYS: .\Mineways.sln
  CHANNELMIXER: .\ChannelMixer\ChannelMixer.sln
  TILEMAKER: .\tilemaker\TileMaker.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

  # Platform to build
  PLATFORM: x64

jobs:
  mineways:
    name: "Mineways build"
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    
    # Starts ChannelMixer
    - name: Restore NuGet ChannelMixer
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.CHANNELMIXER}}

    - name: Build ChannelMixer
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.CHANNELMIXER}} /p:Platform=${{env.PLATFORM}}

    # Starts TileMaker
    - name: Restore NuGet Tilemaker
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.TILEMAKER}}

    - name: Build TileMaker
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.TILEMAKER}} /p:Platform=${{env.PLATFORM}}

    # Starts Mineways
    - name: Restore NuGet Mineways
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.MINEWAYS}}

    - name: Build Mineways
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.MINEWAYS}} /p:Platform=${{env.PLATFORM}}

    - name: Zip Release
      uses: zip -r release.zip . -i ".gitignore" "file.lst" "make_rar.bat" "*.py" "*.c" "*.h" "*.sln" "README.*" "Win\*.cpp" "Win\*.h" "Win\*.rc" "Win\*.lib" "Win\*.vcxproj" "Win\teapot.ico" "Win\terrainExt.png" "Win\sketchfab_banner.bmp" "dependencies\curl\include\*" "dependencies\curl\lib\win32\*" "dependencies\curl\lib\win64\*" "dependencies\openssl\lib\win32\*" "dependencies\openssl\lib\win64\*" "dependencies\picojson\*" "docs\*" "docs\images\*"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release
        path: .\release.zip
        # path: .\x64\Release\
        if-no-files-found: error
        
